export const mockProducts = [
  {
    id: 1,
    name: "Premium Cotton T-Shirt",
    brand: "StyleCo",
    price: 29.99,
    originalPrice: 39.99,
    category: "Clothing",
    description: "Comfortable premium cotton t-shirt perfect for everyday wear.",
    image: "/placeholder.svg?height=400&width=300&text=T-Shirt",
    rating: 4.5,
    reviews: 128,
    inStock: true,
    isOnSale: true,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Navy"],
  },
  {
    id: 2,
    name: "Designer Jeans",
    brand: "DenimPro",
    price: 89.99,
    originalPrice: 120.0,
    category: "Clothing",
    description: "High-quality designer jeans with perfect fit and comfort.",
    image: "/placeholder.svg?height=400&width=300&text=Jeans",
    rating: 4.7,
    reviews: 89,
    inStock: true,
    isOnSale: true,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Blue", "Black", "Gray"],
  },
  {
    id: 3,
    name: "Leather Handbag",
    brand: "LuxBags",
    price: 199.99,
    category: "Accessories",
    description: "Elegant leather handbag perfect for any occasion.",
    image: "/placeholder.svg?height=400&width=300&text=Handbag",
    rating: 4.8,
    reviews: 156,
    inStock: true,
    isOnSale: false,
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
  },
  {
    id: 4,
    name: "Running Shoes",
    brand: "SportMax",
    price: 129.99,
    originalPrice: 159.99,
    category: "Shoes",
    description: "Comfortable running shoes with advanced cushioning technology.",
    image: "/placeholder.svg?height=400&width=300&text=Shoes",
    rating: 4.6,
    reviews: 203,
    inStock: true,
    isOnSale: true,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Blue", "Red"],
  },
  {
    id: 5,
    name: "Silk Scarf",
    brand: "ElegantWear",
    price: 49.99,
    category: "Accessories",
    description: "Luxurious silk scarf with beautiful patterns.",
    image: "/placeholder.svg?height=400&width=300&text=Scarf",
    rating: 4.4,
    reviews: 67,
    inStock: true,
    isOnSale: false,
    sizes: ["One Size"],
    colors: ["Red", "Blue", "Green", "Purple"],
  },
  {
    id: 6,
    name: "Wool Sweater",
    brand: "CozyKnits",
    price: 79.99,
    originalPrice: 99.99,
    category: "Clothing",
    description: "Warm and comfortable wool sweater for cold weather.",
    image: "/placeholder.svg?height=400&width=300&text=Sweater",
    rating: 4.3,
    reviews: 94,
    inStock: true,
    isOnSale: true,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Navy", "Burgundy", "Cream"],
  },
]

export const mockCategories = [
  { id: 1, name: "Clothing", count: 45 },
  { id: 2, name: "Accessories", count: 23 },
  { id: 3, name: "Shoes", count: 18 },
  { id: 4, name: "Bags", count: 12 },
]

export const mockOrders = [
  {
    id: "ORD-2024-001",
    date: "2024-01-15",
    total: 159.98,
    status: "delivered",
    items: [
      {
        id: 1,
        name: "Premium Cotton T-Shirt",
        price: 29.99,
        quantity: 2,
        image: "/placeholder.svg?height=60&width=60",
      },
      { id: 2, name: "Designer Jeans", price: 89.99, quantity: 1, image: "/placeholder.svg?height=60&width=60" },
    ],
  },
  {
    id: "ORD-2024-002",
    date: "2024-01-10",
    total: 89.99,
    status: "shipped",
    items: [
      { id: 3, name: "Leather Handbag", price: 199.99, quantity: 1, image: "/placeholder.svg?height=60&width=60" },
    ],
  },
  {
    id: "ORD-2024-003",
    date: "2024-01-05",
    total: 249.97,
    status: "processing",
    items: [
      { id: 4, name: "Running Shoes", price: 129.99, quantity: 1, image: "/placeholder.svg?height=60&width=60" },
      { id: 5, name: "Silk Scarf", price: 49.99, quantity: 2, image: "/placeholder.svg?height=60&width=60" },
    ],
  },
]
