export const mockProducts = [
  {
    id: 1,
    name: "Elegant Silk Dress",
    price: 299.99,
    originalPrice: 399.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Dresses",
    brand: "Luxe Collection",
    rating: 4.8,
    reviews: 124,
    description:
      "A stunning silk dress perfect for special occasions. Features a flowing silhouette and premium silk fabric.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy"],
    inStock: true,
    isOnSale: true,
  },
  {
    id: 2,
    name: "Classic Leather Jacket",
    price: 449.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Jackets",
    brand: "Urban Style",
    rating: 4.9,
    reviews: 89,
    description: "Premium leather jacket with a timeless design. Perfect for adding edge to any outfit.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
    inStock: true,
    isOnSale: false,
  },
  {
    id: 3,
    name: "Designer Handbag",
    price: 199.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Accessories",
    brand: "Luxe Bags",
    rating: 4.7,
    reviews: 156,
    description: "Elegant designer handbag crafted from premium materials. Features multiple compartments.",
    sizes: ["One Size"],
    colors: ["Black", "Tan", "White"],
    inStock: true,
    isOnSale: false,
  },
  {
    id: 4,
    name: "Casual Denim Jeans",
    price: 89.99,
    originalPrice: 129.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Jeans",
    brand: "Denim Co",
    rating: 4.6,
    reviews: 203,
    description: "Comfortable and stylish denim jeans with a perfect fit. Made from premium denim fabric.",
    sizes: ["26", "28", "30", "32", "34", "36"],
    colors: ["Blue", "Black", "Light Blue"],
    inStock: true,
    isOnSale: true,
  },
  {
    id: 5,
    name: "Luxury Watch",
    price: 599.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Accessories",
    brand: "Time Luxe",
    rating: 4.9,
    reviews: 67,
    description: "Sophisticated luxury watch with Swiss movement. Features sapphire crystal and leather strap.",
    sizes: ["One Size"],
    colors: ["Gold", "Silver", "Rose Gold"],
    inStock: true,
    isOnSale: false,
  },
  {
    id: 6,
    name: "Cozy Knit Sweater",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Sweaters",
    brand: "Comfort Wear",
    rating: 4.5,
    reviews: 98,
    description: "Soft and cozy knit sweater perfect for cooler weather. Made from premium wool blend.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Gray", "Navy"],
    inStock: true,
    isOnSale: false,
  },
]

export const mockCategories = [
  { id: 1, name: "Dresses", count: 45 },
  { id: 2, name: "Jackets", count: 32 },
  { id: 3, name: "Accessories", count: 67 },
  { id: 4, name: "Jeans", count: 28 },
  { id: 5, name: "Sweaters", count: 41 },
  { id: 6, name: "Shoes", count: 53 },
]

export const mockOrders = [
  {
    id: "ORD-001",
    date: "2024-01-15",
    status: "Delivered",
    total: 299.99,
    items: [
      { id: 1, name: "Elegant Silk Dress", price: 299.99, quantity: 1, image: "/placeholder.svg?height=100&width=100" },
    ],
  },
  {
    id: "ORD-002",
    date: "2024-01-10",
    status: "Shipped",
    total: 539.98,
    items: [
      {
        id: 2,
        name: "Classic Leather Jacket",
        price: 449.99,
        quantity: 1,
        image: "/placeholder.svg?height=100&width=100",
      },
      { id: 6, name: "Cozy Knit Sweater", price: 89.99, quantity: 1, image: "/placeholder.svg?height=100&width=100" },
    ],
  },
]

export const mockUser = {
  id: 1,
  name: "Sarah Johnson",
  email: "sarah.johnson@example.com",
  phone: "+1 (555) 123-4567",
  address: {
    street: "123 Fashion Ave",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "United States",
  },
  joinDate: "2023-06-15",
}

export const mockReviews = [
  {
    id: 1,
    productId: 1,
    userName: "Emma Wilson",
    rating: 5,
    comment: "Absolutely love this dress! The quality is amazing and it fits perfectly.",
    date: "2024-01-20",
  },
  {
    id: 2,
    productId: 1,
    userName: "Michael Chen",
    rating: 4,
    comment: "Great dress, fast shipping. Would recommend!",
    date: "2024-01-18",
  },
]
